### PR TITLE
add support for Clear Linux OS

### PR DESCRIPTION
**Pull request by grothja**
This PR adds basic support for Intel's [Clear Linux OS](https://clearlinux.org).  This includes:

- service management via systemd
- managing packages (bundles, in Clear Linux terminology)

The bundles/packages are not versioned, but potentially updated as the entire OS is updated to a new release.

I tested this by building `mitamae` against my branch:

```
conf.gem github: 'grothja/mruby-specinfra',  checksum_hash: '4ea379075dcfffe893832af5e1c3361e4e37cb5a'
```

Going to the directory where `mitamae` was built and starting up a full privs test container to verify service management:

```
docker run --rm -d \
  --name clearlinuxos \
  -e container=docker \
  --tmpfs /run \
  --tmpfs /tmp \
  -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  -v $PWD:/root \
  --cap-add SYS_ADMIN \
  -p 8080:80 \
  clearlinux /sbin/init
```

and then running:

```
docker exec -it clearlinuxos /root/mitamae local /root/test.rb
```

Test I used was this (with various removed, stop, etc. combinations):

```ruby
package "httpd" do
  action :install
end

service "httpd" do
  action :start
end
```

And `curl http://localhost:8080` should return results.

### CODE REVIEW

**Comment by k0kubun** [comment]
This looks good, but this repository is meant to be a port of https://github.com/mizzy/specinfra. Could you file the same PR to the repository first? Once it's merged, I'll merge this PR too.

**Comment by grothja** [comment]
Thanks @k0kubun; per your suggestion, this has made its way into `mizzy/specinfra`.  A couple modifications were made to the name and how OS detection works, but those changes are reflected here now.

**Comment by k0kubun** [comment]
Thank you!

I'll include this in a new mitamae release a few days later because I'm going to a vacation and not carrying my laptop.

**Comment by k0kubun** [comment]
This will be released as mitamae v1.7.8 in [this Travis build](https://travis-ci.org/itamae-kitchen/mitamae/builds/561071257).

**Pull request merged**
